logLevel = "DEBUG"

[entryPoints]
    [entryPoints.udp]
      address = ":8080"
      udp = true

[file]

[frontends]
    [frontends.udpfrontend]
      backend = "udpbackend"

[backends]
    [backends.udpbackend]
      udp = true
      [backends.udpbackend.servers.server1]
        url = "localhost:9051"
      [backends.udpbackend.servers.server2]
        url = "localhost:9052"
      [backends.udpbackend.servers.server3]
        url = "localhost:9053"
